version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: blogdb
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: node-backend
    working_dir: /app
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: ''
      DB_NAME: blogdb
    volumes:
      - ./backend:/app
    networks:
      - app-network
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: react-frontend
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    ports:
      - "80:80"

networks:
  app-network:

volumes:
  db_data:
